name: Github Pages Deploy

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.17]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install and build
        working-directory: ./codewars-activity
        run: npm install && npm run gh-build && cp dist/codewars/index.html dist/codewars/404.html
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: main
          folder: docs # The folder the action should deploy.       
