name: Angualr deploy
on:
  push:
    branches: ["main"]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: actions/checkout@v3
        
      - name: Dowload depds
        run: npm ci
        
      - name: run build
        run: npm run build
        
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with: 
          path: docs
          name: build-file
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: docs
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: Get build project 
        uses: actions/download-artifact@v3
        with: 
          path: build-file
          
    
