name: Angular deploy
on: [ push, workflow_dispatch ]
jobs:
  build_app:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci
      - name: build the project
        run: npm run build
      - name: Upload artifact
        uses: upload-artifact@v3
        with:
          path: dist/codewars
          name: build file
